### ISSUE TITLE
audio out or mini speaker onboard

### ISSUE THREAD

**Issue by Magnetrix** [DonSuperfo/Xberry-Pi#1]
Hi Don,
Is there any chance to have maybe on next batch audio out pins for conecting a mini speaker like the real spectrum next, or maybe an internal speaker ??? 

Thanks

**Comment by DonSuperfo** [comment]
Hi, Yes, it already has, see attached picture.Thanks,DonOn Aug 9, 2023, at 5:00 PM, Magnetrix ***@***.***> wrote:﻿
Hi Don,
Is there any chance to have maybe on next batch audio out pins for conecting a mini speaker like the real spectrum next, or maybe an internal speaker ???
Thanks

**Comment by Magnetrix** [comment]
Thanks Don...
