### ISSUE TITLE
Scart cable?

### ISSUE THREAD

**Issue by ghost** [DonSuperfo/Xberry-Pi#2]
Hi,

Is it possible to wire a scart cable to the RGB and (v?)sync of J12? I can see I could get composite from that header, but RGB on scart would be nicer.

Thanks!
Chris

**Comment by DonSuperfo** [comment]
Hi, 
Yes, you can use RGB, HSYNC, +5V and GND
Refer to this diagram (not for 12 but just an idea) https://github.com/DonSuperfo/Xberry-Pi/blob/main/Issue%204C/Connector.pdf
You also can get all signal from VGA connector, like original ZX Spectrum Next

Thanks,
Don

**Comment by DonSuperfo** [comment]
Hi Chris, 

Yes, you can use RGB, HSYNC, +5V and GND
Refer to this diagram (not for 12 but just an idea) 

https://github.com/DonSuperfo/Xberry-Pi/blob/main/Issue%204C/Connector.pdf

You also can get all signal from VGA connector, like original ZX Spectrum Next

Thanks,
Don

    On Thursday, November 16, 2023 at 09:35:19 AM PST, moochris ***@***.***> wrote:  
 
 


Hi,

Is it possible to wire a scart cable to the RGB and (v?)sync of J12? I can see I could get composite from that header, but RGB on scart would be nicer.

Thanks!
Chris

**Comment by ghost** [comment]
Hi Don,

Thanks - that's very helpful :)
Chris
